CREATE TABLE article (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nickname VARCHAR(20) NOT NULL,
    title VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_on DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);
CREATE TABLE comment (
    id INT PRIMARY KEY AUTO_INCREMENT,
    article_id INT NOT NULL,
    comment_id INT,
    nickname VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified_on DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (article_id) REFERENCES article(id) ON UPDATE CASCADE,
    FOREIGN KEY (comment_id) REFERENCES comment(id) ON UPDATE CASCADE
);